-- Database: "ControlUniversitario"

-- DROP DATABASE "ControlUniversitario";

CREATE DATABASE "ControlUniversitario"
	WITH OWNER = postgres
		ENCODING = 'UTF8'
		TABLESPACE = pg_default
		LC_COLLATE = 'English_United States.1252'  -- Ubicaciones
		LC_CTYPE = 'English_United States.1252'
		CONNECTION LIMIT = -1; -- Limitar las conexiones

CREATE SCHEMA Datos 
CREATE SCHEMA Asignatura

CREATE TABLE Datos.Carrera
(
	IdCarrera BIGSERIAL NOT NULL,
	Nombre VARCHAR(80) NOT NULL,

	CONSTRAINT PK_CARRERA PRIMARY KEY(IdCarrera)
)

CREATE TABLE Datos.Alumno
(
	IdAlumno BIGSERIAL NOT NULL,
	IdCarrera BIGINT NOT NULL,
	Nombre VARCHAR(80) NOT NULL,
	Edad BIGINT NOT NULL,
	Email VARCHAR(50),
  
	CONSTRAINT PK_ALUMNO PRIMARY KEY(IdAlumno),
	CONSTRAINT FK_CARRERA FOREIGN KEY(IdCarrera) REFERENCES Datos.Carrera(IdCarrera)
)

DROP TABLE Datos.Alumno

ALTER TABLE Datos.Alumno ADD CONSTRAINT UQ_EMAIL UNIQUE(Email)
ALtER TABLE Datos.Alumno ADD CONSTRAINT CH_EDAD CHECK (Edad >= 16)

CREATE TABLE Asignatura.Grupo
(
	IdGrupo BIGSERIAL NOT NULL,
	NombreAsignatura VARCHAR(30) NOT NULL,
	NombreProfesor VARCHAR(80) NOT NULL,
	Capacidad INT NOT NULL,
	Dias VARCHAR(15) NOT NULL,
	Horario VARCHAR(15) NOT NULL,

	CONSTRAINT PK_GRUPO PRIMARY KEY (IdGrupo)
)

CREATE TABLE Asignatura.Inscripcion
(
	IdInscripcion BIGSERIAL NOT NULL,
	IdAlumno BIGINT NOT NULL,
	IdGrupo BIGINT NOT NULL,
	Fecha DATE,
	Calificacion INT NOT NULL,
	
	CONSTRAINT PK_INSCRIPCION PRIMARY KEY (IdGrupo),
	CONSTRAINT FK_ALUMNO FOREIGN KEY(IdAlumno) REFERENCES Datos.Alumno(IdAlumno),
	CONSTRAINT FK_GRUPO FOREIGN KEY(IdGrupo) REFERENCES Asignatura.Grupo(IdGrupo)
)

CREATE TABLE Asignatura.Asistencia
(
	IdAlumno BIGINT NOT NULL,
	IdGrupo BIGINT NOT NULL,
	Fecha DATE,
	
	CONSTRAINT FK_ALUMNO_AS FOREIGN KEY(IdAlumno) REFERENCES Datos.Alumno(IdAlumno),
	CONSTRAINT FK_GRUPO_AS FOREIGN KEY(IdGrupo) REFERENCES Asignatura.Grupo(IdGrupo)
)

SELECT * FROM Datos.Carrera

-- Crear usuario administrador
CREATE ROLE ADMIN WITH LOGIN ENCRYPTED PASSWORD '1234'
GRANT CONNECT ON DATABASE "ControlUniversitario" TO ADMIN
GRANT USAGE ON SCHEMA Datos TO ADMIN
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA Datos TO ADMIN
GRANT SELECT ON ALL TABLES IN SCHEMA Datos TO ADMIN
GRANT INSERT ON ALL TABLES IN SCHEMA Datos TO ADMIN

-- SELEC desde ADMIN
SELECT * FROM Datos.carrera
INSERT INTO Datos.carrera (nombre) VALUES ('ASDASDAD')
SELECT * FROM Datos.carrera

DELETE FROM datos.carrera WHERE idCarrera = 1


-- Crear otro usuario consultor sin persmiso de insertar
CREATE ROLE CONSULTOR WITH LOGIN ENCRYPTED PASSWORD '1234'
GRANT CONNECT ON DATABASE "ControlUniversitario" TO CONSULTOR
GRANT USAGE ON SCHEMA datos TO CONSULTOR
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA Datos TO CONSULTOR
GRANT SELECT ON ALL TABLES IN SCHEMA Datos TO CONSULTOR
GRANT DELETE ON ALL TABLES IN SCHEMA Datos TO CONSULTOR
REVOKE INSERT ON ALL TABLES IN SCHEMA Datos FROM CONSULTOR

SELECT * FROM Datos.Carrera
INSERT INTO Datos.Carrera(Nombre) Values('carrera1')
DELETE FROM datos.carrera WHERE IdCarrera = 1

DELETE FROM Datos.carrera